import { Component, effect, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { TmdbEpisode } from '../../core/models/tmdb.models';
import { UserShowWatchlist } from '../../core/models/user.models';
import { TmdbService } from '../../core/services/tmdb.service';
import { WatchlistService } from '../../core/services/watchlist.service';
import { forkJoin } from 'rxjs';

type Filter = 'up_next' | 'not_started' | 'finished';

@Component({
  imports: [RouterLink],
  template: `<section class="content"><header class="page-head"><div><p class="eyebrow">Your personal queue</p><h1>Keep watching.</h1></div><div class="head-actions"><a class="button" routerLink="/search">+ Add a show</a></div></header><div class="filters" role="tablist">@for (filter of filters; track filter.key) { <button [class.selected]="active() === filter.key" (click)="active.set(filter.key)">{{ filter.label }} <span>{{ count(filter.key) }}</span></button> }</div>@if (visibleShows().length) { <div class="watch-grid">@for (show of visibleShows(); track show.showId) { <article class="watch-card"><a [routerLink]="['/show', show.showId]"><img [src]="tmdb.image(show.posterPath)" [alt]="show.showName + ' poster'"><div class="watch-copy"><p class="eyebrow">{{ show.status === 'completed' ? 'Finished' : show.status === 'not_started' ? 'Not started' : 'Up next' }}</p><h2>{{ show.showName }}</h2><p class="muted">{{ show.watchedEpisodesCount }} of {{ show.totalEpisodes || '?' }} episodes watched</p>@if (nextEpisode(show); as next) { <p class="next-episode">Next: S{{ next.season_number }} · E{{ next.episode_number }} · {{ next.name }}</p> }<div class="progress"><span [style.width.%]="progress(show)"></span></div></div></a></article> }</div> } @else { <div class="empty"><span class="empty-mark">+</span><h2>Your queue is quiet.</h2><p class="muted">Discover a series and make it yours.</p><a class="button" routerLink="/search">Browse shows</a></div> }</section>`,
  styles: [`.page-head{display:flex;justify-content:space-between;align-items:end;gap:1rem;margin-bottom:2rem}.head-actions{display:flex;gap:.5rem;align-items:center}.head-actions button:disabled{cursor:not-allowed;opacity:.45}.filters{display:flex;gap:.35rem;overflow:auto;margin-bottom:1.5rem}.filters button{white-space:nowrap;background:transparent;border:1px solid var(--line);border-radius:6px;color:var(--muted);padding:.6rem .75rem}.filters button.selected{color:var(--ink);background:var(--lime);border-color:var(--lime)}.filters span{font:.7rem var(--mono);margin-left:.3rem}.watch-grid{display:grid;gap:1rem;max-width:800px}.watch-card{background:var(--panel);border:1px solid var(--line);border-radius:9px;overflow:hidden}.watch-card a{display:grid;grid-template-columns:130px 1fr;color:inherit;text-decoration:none}.watch-card img{width:100%;height:190px;object-fit:cover}.watch-copy{padding:1.2rem;align-self:center}.watch-copy h2{margin:.4rem 0}.watch-copy .muted{font-size:.82rem}.next-episode{margin:.8rem 0 0;color:var(--lime);font-size:.8rem;line-height:1.4}.progress{height:5px;background:var(--line);margin-top:1.1rem;border-radius:5px;overflow:hidden}.progress span{display:block;height:100%;background:var(--lime)}.empty{min-height:45vh;display:grid;place-content:center;justify-items:center;gap:1rem;text-align:center}.empty-mark{font-size:3rem;color:var(--lime)}@media(max-width:600px){.content{padding-top:2rem}.page-head{align-items:start}.head-actions{flex-wrap:wrap;justify-content:flex-end}.head-actions .button{font-size:.78rem}.watch-card a{grid-template-columns:90px 1fr}.watch-card img{height:135px}.watch-copy{padding:.9rem}.watch-copy h2{font-size:1.15rem}}`],
})
export class WatchlistComponent {
  readonly tmdb = inject(TmdbService); readonly store = inject(WatchlistService); readonly active = signal<Filter>('up_next'); readonly filters: { key: Filter; label: string }[] = [{ key: 'up_next', label: 'Up next' }, { key: 'not_started', label: 'Not started' }, { key: 'finished', label: 'Finished' }]; readonly episodeCatalog = signal<Record<number, TmdbEpisode[]>>({}); private readonly loadingCatalog = new Set<number>();
  constructor() { this.store.load(); effect(() => { for (const show of this.store.shows()) { if (!(show.showId in this.episodeCatalog()) && !this.loadingCatalog.has(show.showId)) this.loadEpisodeCatalog(show.showId); } }); }
  visibleShows(): UserShowWatchlist[] { return this.store.shows().filter((show) => this.active() === 'up_next' ? show.status === 'watching' : this.active() === 'not_started' ? show.status === 'not_started' : show.status === 'completed'); }
  count(filter: Filter): number { return this.store.shows().filter((show) => filter === 'up_next' ? show.status === 'watching' : filter === 'not_started' ? show.status === 'not_started' : show.status === 'completed').length; }
  progress(show: UserShowWatchlist): number { return show.totalEpisodes ? Math.round(show.watchedEpisodesCount / show.totalEpisodes * 100) : 0; }
  nextEpisode(show: UserShowWatchlist): TmdbEpisode | null { const watched = this.store.watched(); return (this.episodeCatalog()[show.showId] ?? []).find((episode) => !watched.some((item) => item.showId === show.showId && item.seasonNumber === episode.season_number && item.episodeNumber === episode.episode_number)) ?? null; }
  private loadEpisodeCatalog(showId: number): void { this.loadingCatalog.add(showId); this.tmdb.getShowDetails(showId).subscribe({ next: (show) => { const seasons = (show.seasons ?? []).filter((season) => season.season_number > 0); if (!seasons.length) { this.episodeCatalog.update((catalog) => ({ ...catalog, [showId]: [] })); this.loadingCatalog.delete(showId); return; } forkJoin(seasons.map((season) => this.tmdb.getSeasonDetails(showId, season.season_number))).subscribe({ next: (details) => { this.episodeCatalog.update((catalog) => ({ ...catalog, [showId]: details.flatMap((season) => season.episodes).sort((first, second) => first.season_number - second.season_number || first.episode_number - second.episode_number) })); this.loadingCatalog.delete(showId); }, error: () => { this.episodeCatalog.update((catalog) => ({ ...catalog, [showId]: [] })); this.loadingCatalog.delete(showId); } }); }, error: () => { this.episodeCatalog.update((catalog) => ({ ...catalog, [showId]: [] })); this.loadingCatalog.delete(showId); } }); }
}
