import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { WatchlistService } from '../../core/services/watchlist.service';

@Component({
  template: `<section class="content profile"><header><p class="eyebrow">Your viewing record</p><h1>Profile.</h1></header><section class="identity"><div class="profile-avatar">{{ auth.user()?.displayName?.slice(0, 1) ?? 'A' }}</div><div><h2>{{ auth.user()?.displayName ?? 'Alvaro' }}</h2><p class="muted">{{ auth.user()?.email }}</p></div></section><div class="stats"><article><strong>{{ store.watched().length }}</strong><span>Episodes watched</span></article><article><strong>{{ store.shows().length }}</strong><span>Shows tracked</span></article><article><strong>{{ hoursWatched() }}h</strong><span>Time in stories</span></article></div><section class="settings"><div><p class="eyebrow">Account</p><h2>Keep your space yours.</h2><p class="muted">Progress syncs privately to your Firebase account.</p></div><button class="button ghost" (click)="logout()">Sign out</button></section></section>`,
  styles: [`.profile{max-width:900px}.profile header{margin-bottom:2.5rem}.identity{display:flex;gap:1rem;align-items:center;padding:1.2rem 0;border-bottom:1px solid var(--line)}.profile-avatar{width:4rem;height:4rem;display:grid;place-items:center;border-radius:50%;background:var(--coral);font-size:1.5rem;font-weight:700}.identity h2{margin-bottom:.3rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin:2rem 0}.stats article{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:1.25rem}.stats strong{display:block;color:var(--lime);font-size:2rem;letter-spacing:-.06em}.stats span{display:block;color:var(--muted);font-size:.78rem;margin-top:.4rem}.settings{display:flex;justify-content:space-between;align-items:center;gap:1rem;padding-top:2rem;border-top:1px solid var(--line)}@media(max-width:600px){.stats{grid-template-columns:1fr 1fr}.stats article:last-child{grid-column:span 2}.settings{align-items:start;flex-direction:column}}`],
})
export class ProfileComponent { readonly auth = inject(AuthService); readonly store = inject(WatchlistService); private readonly router = inject(Router); constructor() { this.store.load(); } hoursWatched(): number { return Math.round(this.store.watched().length * 0.7); } async logout(): Promise<void> { await this.auth.signOut(); await this.router.navigateByUrl('/login'); } }
