import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { TmdbEpisode, TmdbSeason, TmdbShowDetails } from '../../core/models/tmdb.models';
import { TmdbService } from '../../core/services/tmdb.service';
import { WatchlistService } from '../../core/services/watchlist.service';

@Component({
  imports: [RouterLink],
  template: `<section class="detail">@if (show(); as current) { <div class="detail-body"><a routerLink="/search" class="back">← Back to discover</a><div class="hero"><img [src]="tmdb.image(current.poster_path)" [alt]="current.name + ' poster'"><div><p class="eyebrow">{{ current.status ?? 'TV series' }}</p><h1>{{ current.name }}</h1><p class="rating">★ {{ current.vote_average.toFixed(1) }}</p><p class="overview">{{ current.overview }}</p><button class="button" (click)="toggleWatchlist()">{{ tracked() ? 'In your watchlist' : '+ Add to watchlist' }}</button></div></div><section class="episodes"><p class="eyebrow">{{ current.number_of_episodes ?? 0 }} episodes</p><h2>Seasons</h2>@for (season of current.seasons ?? []; track season.id) { <div class="season"><button class="season-title" (click)="loadSeason(season)">{{ season.name }} · {{ season.episode_count }} episodes</button>@if (selectedSeason() === season.season_number) { @for (episode of episodes(); track episode.id) { <article class="episode" (touchend)="onSwipe($event, episode)"><div><strong>{{ episode.episode_number }}. {{ episode.name }}</strong><p class="muted">{{ episode.air_date || 'No air date' }} · ★ {{ episode.vote_average.toFixed(1) }}</p><p class="snippet">{{ episode.overview || 'No overview available.' }}</p></div><button class="check" (click)="toggleEpisode(episode)" [attr.aria-label]="'Toggle watched for ' + episode.name">{{ isWatched(episode) ? '✓' : '○' }}</button></article> } } </div> }</section></div> } @else { <div class="loading">Loading show...</div> }</section>`,
  styles: [`.detail-body{max-width:1000px;margin:0 auto;padding:3rem clamp(1.1rem,4vw,4rem) 6rem}.back{color:var(--muted);text-decoration:none;font-size:.8rem}.hero{display:grid;grid-template-columns:190px 1fr;gap:2rem;align-items:end;margin:2rem 0 4rem}.hero img{width:100%;aspect-ratio:2/3;object-fit:cover;border-radius:8px}.hero h1{margin:.5rem 0 1rem}.rating{color:var(--lime);font-weight:700}.overview{max-width:650px;color:var(--muted);line-height:1.6;margin:1rem 0 1.4rem}.episodes{max-width:800px}.episodes h2{margin:.4rem 0 1rem}.season{border-top:1px solid var(--line)}.season-title{width:100%;background:none;border:0;color:var(--paper);padding:1rem 0;text-align:left}.episode{display:grid;grid-template-columns:1fr 2rem;gap:.8rem;padding:1rem 0;border-top:1px solid var(--line);touch-action:pan-y}.episode .muted,.snippet{font-size:.75rem}.snippet{color:var(--muted);margin-top:.5rem}.check{border:0;background:none;color:var(--lime);font-size:1.3rem}.loading{text-align:center;padding:4rem}@media(max-width:600px){.detail-body{padding-top:2rem}.hero{grid-template-columns:100px 1fr;gap:1rem}.hero h1{font-size:2rem}.overview{grid-column:span 2}.hero .button{grid-column:span 2}}`],
})
export class ShowDetailsComponent {
  readonly tmdb = inject(TmdbService); private readonly route = inject(ActivatedRoute); private readonly store = inject(WatchlistService); readonly show = signal<TmdbShowDetails | null>(null); readonly episodes = signal<TmdbEpisode[]>([]); readonly selectedSeason = signal<number | null>(null); readonly tracked = signal(false);
  constructor() { const id = Number(this.route.snapshot.paramMap.get('id')); this.tmdb.getShowDetails(id).subscribe((show) => { this.show.set(show); this.tracked.set(this.store.shows().some((item) => item.showId === show.id)); }); }
  loadSeason(season: TmdbSeason): void { this.selectedSeason.set(this.selectedSeason() === season.season_number ? null : season.season_number); if (this.selectedSeason() !== null) this.tmdb.getSeasonDetails(this.show()?.id ?? 0, season.season_number).subscribe((details) => this.episodes.set(details.episodes)); }
  isWatched(episode: TmdbEpisode): boolean { return this.store.watched().some((item) => item.showId === this.show()?.id && item.seasonNumber === episode.season_number && item.episodeNumber === episode.episode_number); }
  toggleEpisode(episode: TmdbEpisode): void { const showId = this.show()?.id; if (showId) this.store.toggleEpisode({ showId, seasonNumber: episode.season_number, episodeNumber: episode.episode_number, watchedAt: new Date().toISOString() }); }
  onSwipe(event: TouchEvent, episode: TmdbEpisode): void { const touch = event.changedTouches[0]; if (touch && touch.clientX > 160) this.toggleEpisode(episode); }
  async toggleWatchlist(): Promise<void> { const show = this.show(); if (!show) return; if (this.tracked()) await this.store.removeShow(show.id); else await this.store.addShow({ showId: show.id, showName: show.name, posterPath: show.poster_path ?? '', status: 'not_started', addedAt: new Date().toISOString(), totalEpisodes: show.number_of_episodes ?? 0, watchedEpisodesCount: 0 }); this.tracked.update((value) => !value); }
}
